### PR TITLE
fix: update components to named functions

### LINKED ISSUE #3: Add named components
https://github.com/eveningkid/react-native-popable/blob/49515ac06b393bfeb8c34358f3cb901c47e76a5b/src/Popable.tsx#L27

Next.js fast refresh breaks with anonymously named components. It could be solved with `export default function Popable`.

This also has[ other implications](https://twitter.com/dan_abramov/status/1255229440860262400?lang=en) for debugging.

I can PR this if you'd like.

### PR DESCRIPTION
**Pull request by eveningkid**
Fix #3.

- Update components to named functions: instead of anonymous functions, turned them into named ones.

### CODE REVIEW

File: src/Popover.tsx [hunk 1]
```diff
@@ -22,7 +22,7 @@ export type PopoverProps = {
   position?: 'top' | 'right' | 'bottom' | 'left';
 } & ViewProps;
 
-export default React.forwardRef<View, PopoverProps>(
+const Popover = React.forwardRef<View, PopoverProps>(
   (
```
Comment (nandorojo) [inline src/Popover.tsx:26]: This should also be a function, not an arrow function, since it won't inherit the name of the outer variable. So it should be `forwardRef(function Popover() {`

**Review by nandorojo — CHANGES_REQUESTED** [review]

**Comment by eveningkid** [comment]
Alright, so this should be ok this time. Let me know

**Comment by eveningkid** [comment]
I'd like to push this @nandorojo. I'll just need to solve the conflict first but I need to know if everything else works for the named components.

If you could just confirm this so this can move forward, thanks

**Comment by nandorojo** [comment]
Yup they look good thanks!

**Comment by eveningkid** [comment]
Thank you, I'll merge it :)
